### ISSUE TITLE
An error occurred (InvalidCiphertextException) when calling the Decrypt operation:

### ISSUE THREAD

**Issue by TheAshwanik** [iann0036/toyxks#1]
Trying this repo. 
I can encrypt the text, 
```
$$ aws kms encrypt --key-id 24fd0513-2f96-405c-937b-7a2f57995c97 --plaintext c2VjcmV0

{
    "CiphertextBlob": "AQICAHh4v9xHRlzyKjDxneMTf8DxM7R/sH6dJr+xylrbXLPI9gECyp5neFwXWLCQ0mBdPPIiAAAAiQIAAAzU5FtUogEET1EJJLUAZvznq62hvgr7l03D4sYyOnodFPqNNCsLsT6KcsxlXw04UdAWxnUxKXshLlmmzL8S4jhepiplq1jxn/knwGCWFAzzY8i2YwsayG6PJAB1RdEWzalm/6EGWhNYIw0OeqkfeDlneI8nmRAdXi4eUqIOu6SqsOsoJKFq",
    "KeyId": "arn:aws:kms:us-east-1:262396174674:key/24fd0513-2f96-405c-937b-7a2f57995c97",
    "EncryptionAlgorithm": "SYMMETRIC_DEFAULT"
}
```

but while decrypting I get the error.

```
$$ aws kms decrypt --ciphertext-blob AQICAHh4v9xHRlzyKjDxneMTf8DxM7R/sH6dJr+xylrbXLPI9gECyp5neFwXWLCQ0mBdPPIiAAAAiQIAAAzU5FtUogEET1EJJLUAZvznq62hvgr7l03D4sYyOnodFPqNNCsLsT6KcsxlXw04UdAWxnUxKXshLlmmzL8S4jhepiplq1jxn/knwGCWFAzzY8i2YwsayG6PJAB1RdEWzalm/6EGWhNYIw0OeqkfeDlneI8nmRAdXi4eUqIOu6SqsOsoJKFq --key-id arn:aws:kms:us-east-1:262396174674:key/24fd0513-2f96-405c-937b-7a2f57995c97

An error occurred (InvalidCiphertextException) when calling the Decrypt operation:
```

**Comment by TheAshwanik** [comment]
This worked:

`(aws kms decrypt --ciphertext-blob fileb://<(echo 'AQICAHh4v9xHRlzyKjDxneMTf8DxM7R/sH6dJr+xylrbXLPI9gH3fPM7ZTZB9whLFp32o0oOAAAAiQIAAAwgdpj47hrjDP5qj+sAZpbdwpORju7SwPQLUCBm5lQLFSc762FILcTm+qedFiKfG3cj0EKsbIGzy9R6ETtWSw1x/MIbup0wiwLFLvM3xw7+nCW5qyRNL5JsnipdAJ8OIRZOjaOSTh+xOiiR92Bq9f17yYpKwRC7XNQwF7TjLm6uVi8Y2Fcf' | base64 -d) --query Plaintext --output text | base64 -d)
`

And this too..


`$ aws kms encrypt --key-id 24fd0513-2f96-405c-937b-7a2f57995c97 --plaintext c2VjcmV0 --query CiphertextBlob --output text  | base64 -d > /tmp/encrypted-file`


```
$ echo "Decrypted: $(aws kms decrypt --ciphertext-blob fileb:///tmp/encrypted-file --query Plaintext --output text | base64 -d)"
Decrypted: c2VjcmV0
```

**Comment by iann0036** [comment]
Hey @TheAshwanik,

Thanks for raising!

Is this consistent? Might be due to characters in the ciphertext blob breaking the argument or something.

**Comment by TheAshwanik** [comment]
Hi @iann0036  , yes the aws kms decrypt  command as you mentioned was consistently failing. 

I guess this was because the when decrypting ciphertext-blob the aws command returned base64 encoded value in plaintext field. So it needed base64 decoding twice.

I used this command, so the  /tmp/encrypted-file  contained the base64 decoded value of   ciphertext-blob 

``` 
echo 'AQICAHh4v9xHRlzyKjDxneMTf8DxM7R/sH6dJr+xylrbXLPI9gH3fPM7ZTZB9whLFp32o0oOAAAAiQIAAAwgdpj47hrjDP5qj+sAZpbdwpORju7SwPQLUCBm5lQLFSc762FILcTm+qedFiKfG3cj0EKsbIGzy9R6ETtWSw1x/MIbup0wiwLFLvM3xw7+nCW5qyRNL5JsnipdAJ8OIRZOjaOSTh+xOiiR92Bq9f17yYpKwRC7XNQwF7TjLm6uVi8Y2Fcf' | base64 -d > /tmp/encrypted-file

```
and then 

```
$(aws kms decrypt --ciphertext-blob fileb:///tmp/encrypted-file --query Plaintext --output text | base64 -d)"
```
